[package]
name = "web-stomp-client"
description = "STOMP client library for frontend apps"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
readme = "README.md"
rust-version = "1.84"

[dependencies]
nom = "8.0"
thiserror = "2.0"
url = "2.5"
web-sys = "0.3"
