[package]
name = "echo"
version = "0.1.0"
edition = "2021"

[dependencies]
console_log = "1.0"
console_error_panic_hook = "0.1"
leptos = { version = "0.8", features = ["csr"] }
log = "0.4"
web-stomp-client = { path = "../.." }
